// Package treedata bundles the versioned passive tree data (generated by
// cmd/treegen from the official GGG skill tree export) into the binary, so the
// graphical tree works out of the box for the shipped game versions.
package treedata

import "embed"

// FS holds the bundled "tree/<version>.json" files.
//
//go:embed tree/*.json
var FS embed.FS

// Dir is the directory within FS that contains the tree files.
const Dir = "tree"
